<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CSM Monthly Summary Report — {{ $monthLabel }}</title>
    <style>
        /* D9.32b: minimal print style, aligned with physical-count-report
           (plain header, light-blue table heads, hairline borders — no
           decorative boxes, callouts, or colour accents). */
        @page { size: A4 portrait; margin: 12mm; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, Helvetica, sans-serif; font-size: 9.5pt; color: #000; line-height: 1.35; }

        .hdr { text-align: center; border-bottom: 2px solid #0038A8; padding-bottom: 6px; margin-bottom: 10px; }
        .hdr h1 { font-size: 14pt; letter-spacing: 1px; }
        .hdr .sub { font-size: 9pt; color: #444; margin-top: 2px; }

        .meta { width: 100%; margin-bottom: 10px; font-size: 9pt; }
        .meta td { padding: 1.5px 4px; vertical-align: top; }
        .meta .lbl { color: #555; width: 110px; }

        table.sum { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        table.sum th, table.sum td { border: 1px solid #999; padding: 3px 6px; text-align: center; font-size: 9pt; }
        table.sum th { background: #eef3fb; }

        .sec { font-size: 10pt; font-weight: bold; letter-spacing: 0.5px; text-transform: uppercase;
               border-bottom: 1px solid #999; padding-bottom: 2px; margin: 12px 0 6px; }

        table.q { width: 100%; border-collapse: collapse; }
        table.q th { background: #eef3fb; border: 1px solid #999; padding: 3px 4px; font-size: 8.5pt; }
        table.q th .sub { display: block; font-size: 7pt; font-weight: normal; color: #555; }
        table.q td { border: 1px solid #bbb; padding: 2.5px 4px; font-size: 8.5pt; text-align: center; }
        table.q td.qq { text-align: left; line-height: 1.25; }
        table.q tr.total td { background: #eef3fb; font-weight: bold; }

        .note { font-size: 8pt; color: #555; margin-top: 4px; line-height: 1.4; }
        .blk { margin-bottom: 8px; font-size: 9.5pt; }
        .blk p { margin: 2px 0; }
        .blk .q-text { font-style: italic; font-weight: bold; }
        .empty { border: 1px solid #999; padding: 10px; font-size: 9.5pt; background: #fafafa; }
        .foot { margin-top: 16px; font-size: 8pt; color: #666; border-top: 1px solid #ccc; padding-top: 4px; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>

    <div class="hdr">
        <h1>CLIENT SATISFACTION MEASUREMENT</h1>
        <div class="sub">Monthly Summary Report — {{ $monthLabel }}</div>
    </div>

    <table class="meta">
        <tr>
            <td class="lbl">Reporting period:</td>
            <td>{{ $monthLabel }}</td>
            <td class="lbl">Date generated:</td>
            <td>{{ now()->format('F j, Y') }}</td>
        </tr>
        <tr>
            <td class="lbl">Scope:</td>
            <td>All branches</td>
            <td class="lbl">Survey responses:</td>
            <td>{{ $respondents }}</td>
        </tr>
    </table>

    @if(!$hasData)
        <div class="empty">
            No survey responses were recorded for {{ $monthLabel }}.
            This report is kept as part of the annual CSM record.
        </div>
        <div class="foot">Generated by the NCMB ICT System &middot; {{ $monthLabel }} &middot; Page 1 of 2</div>
    @else
        <div class="sec">Monthly Summary</div>
        <table class="sum">
            <tr>
                <th>Overall Rating</th>
                <th>Rating Description</th>
                <th>% Satisfied</th>
                <th>Responses</th>
                <th>Completed Requests</th>
                <th>Response Rate</th>
            </tr>
            <tr>
                <td><b>{{ $overall !== null ? number_format($overall, 1) : '—' }}</b>{{ $overall !== null ? ' / 5' : '' }}</td>
                <td>{{ $overall !== null ? $band['label'] : '—' }}</td>
                <td>{{ $satisfiedPct !== null ? $satisfiedPct . '%' : '—' }}</td>
                <td>{{ $respondents }}</td>
                <td>{{ $completedCount }}</td>
                <td>{{ $responseRate !== null ? $responseRate . '%' : '—' }}</td>
            </tr>
        </table>

        <div class="sec">How Each Question Was Answered</div>
        <table class="q">
            <tr>
                <th style="width:38%;">Question</th>
                <th>5<span class="sub">Strongly Agree</span></th>
                <th>4<span class="sub">Agree</span></th>
                <th>3<span class="sub">Not sure</span></th>
                <th>2<span class="sub">Disagree</span></th>
                <th>1<span class="sub">Strongly Dis.</span></th>
                <th style="width:9%;">Average</th>
                <th style="width:13%;">Rating</th>
            </tr>
            @foreach($questions as $row)
                <tr>
                    <td class="qq">{{ $row['question'] }}</td>
                    @foreach([5,4,3,2,1] as $s)
                        <td>{{ $row['counts'][$s] }}</td>
                    @endforeach
                    <td>{{ $row['average'] !== null ? number_format($row['average'], 1) : '—' }}</td>
                    <td>{{ $row['average'] !== null ? $row['band']['label'] : '—' }}</td>
                </tr>
            @endforeach
            <tr class="total">
                <td class="qq">OVERALL SATISFACTION RATING</td>
                <td colspan="5"></td>
                <td>{{ $overall !== null ? number_format($overall, 1) : '—' }}</td>
                <td>{{ $overall !== null ? $band['label'] : '—' }}</td>
            </tr>
        </table>
        <div class="note">
            Scale: 5 = Strongly Agree &middot; 4 = Agree &middot; 3 = Neither Agree nor Disagree &middot; 2 = Disagree &middot; 1 = Strongly Disagree.
            Blank answers (N/A) are not counted.<br>
            Rating: 4.21&ndash;5.00 Very Satisfied &middot; 3.41&ndash;4.20 Satisfied &middot; 2.61&ndash;3.40 Not Sure &middot; 1.81&ndash;2.60 Dissatisfied &middot; 1.00&ndash;1.80 Very Dissatisfied.
        </div>

        <div class="page-break"></div>

        <div class="hdr">
            <h1>CLIENT SATISFACTION MEASUREMENT</h1>
            <div class="sub">Monthly Summary Report — {{ $monthLabel }} (continued)</div>
        </div>

        <div class="sec">What We Need to Improve</div>
        @if($weakest)
            <div class="blk">
                <p>The clients rated this question the lowest ({{ number_format($weakest['average'], 1) }} — {{ $weakest['band']['label'] }}):</p>
                <p class="q-text">&ldquo;{{ $weakest['question'] }}&rdquo;</p>
                <p>{{ $weakest['disagreeCount'] }} of {{ $respondents }} respondent(s)
                    ({{ $respondents > 0 ? round(($weakest['disagreeCount'] / $respondents) * 100) : 0 }}%)
                    answered Disagree or Strongly Disagree.</p>
                @if($weakest['prevAverage'] !== null)
                    <p>Compared to last month it
                        @if($weakest['average'] < $weakest['prevAverage'])
                            went down ({{ number_format($weakest['prevAverage'], 1) }} &rarr; {{ number_format($weakest['average'], 1) }}).
                        @elseif($weakest['average'] > $weakest['prevAverage'])
                            went up ({{ number_format($weakest['prevAverage'], 1) }} &rarr; {{ number_format($weakest['average'], 1) }}).
                        @else
                            stayed the same ({{ number_format($weakest['average'], 1) }}).
                        @endif
                    </p>
                @else
                    <p>No prior-month sample to compare with yet.</p>
                @endif
                <p>Recommended action: review the process behind this question with the team,
                    then check next month's report to confirm the rating improves.</p>
            </div>
        @endif
        @if($secondWeakest && $weakest && $secondWeakest['column'] !== $weakest['column'] && $secondWeakest['average'] !== null)
            <div class="blk">
                <p>Second-lowest: <span class="q-text">&ldquo;{{ $secondWeakest['question'] }}&rdquo;</span>
                    &mdash; {{ number_format($secondWeakest['average'], 1) }} ({{ $secondWeakest['band']['label'] }}),
                    {{ $secondWeakest['disagreeCount'] }} disagree answer(s).</p>
            </div>
        @endif

        @if($goodNews)
            <div class="sec">Highest-Rated Questions</div>
            <div class="blk">
                @foreach($goodNews as $row)
                    <p>&bull; &ldquo;{{ $row['question'] }}&rdquo; &mdash; {{ number_format($row['average'], 1) }} ({{ $row['band']['label'] }})</p>
                @endforeach
            </div>
        @endif

        <div class="sec">Respondent Profile</div>
        <table class="sum">
            <tr>
                <th>Male</th>
                <th>Female</th>
                <th>Not specified</th>
                <th>Total</th>
            </tr>
            <tr>
                @php $others = $respondents - $male - $female; @endphp
                <td>{{ $male }}</td>
                <td>{{ $female }}</td>
                <td>{{ $others > 0 ? $others : 0 }}</td>
                <td>{{ $respondents }}</td>
            </tr>
        </table>

        <div class="foot">Generated by the NCMB ICT System &middot; {{ $monthLabel }} &middot; Page 2 of 2</div>
    @endif

</body>
</html>