<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSM Monthly Summary Report — {{ $monthLabel }}</title>
    <style>
        /* D9.32c: same visual language as pdf/csm-form.blade.php — NCMB
           letterhead (logo + navy title), thin grey table borders, plain
           white background. No decorative boxes or colour accents. */
        @page { size: A4 portrait; margin: 9mm; }
        body { font-family: Arial, sans-serif; font-size: 9.5px; color: #333; line-height: 1.3; padding: 6px 8px; }
        .header-bar { border-bottom: 2px solid #0f2a6b; padding-bottom: 4px; margin-bottom: 6px; }
        .header-bar table { width: 100%; border-collapse: collapse; }
        .header-bar td { border: none; vertical-align: middle; padding: 0; }
        .logo { width: 44px; height: 44px; }
        .agency { font-size: 17px; font-weight: bold; color: #0f2a6b; }
        .form-title { font-size: 10px; font-weight: bold; letter-spacing: 0.6px; text-transform: uppercase; }
        .meta { font-size: 10px; margin-bottom: 6px; }
        .meta b { color: #0f2a6b; }
        .section-title { font-size: 11px; font-weight: bold; color: #0f2a6b; margin: 8px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
        .rpt-table { width: 100%; border-collapse: collapse; }
        .rpt-table th, .rpt-table td { border: 1px solid #cbd5e1; padding: 3px 4px; text-align: center; font-size: 9px; }
        .rpt-table th { font-size: 8px; font-weight: bold; text-transform: uppercase; background: #f8fafc; }
        .rpt-table th .sub { display: block; font-size: 7px; font-weight: normal; color: #666; text-transform: none; }
        .rpt-table td.q { text-align: left; width: 38%; font-size: 10px; line-height: 1.25; }
        .rpt-table td.avg, .rpt-table td.rate { font-weight: bold; font-size: 10px; }
        .rpt-table tr.total td { background: #f1f5f9; font-weight: bold; font-size: 10px; }
        .note { font-size: 8px; color: #666; margin-top: 4px; line-height: 1.4; }
        .sec { margin-bottom: 6px; }
        .sec p { margin: 2px 0; font-size: 10px; }
        .sec .q-text { font-style: italic; font-weight: bold; font-size: 10.5px; color: #1f2937; }
        .page-break { page-break-after: always; }
        .footer { border-top: 1px solid #cbd5e1; margin-top: 14px; padding-top: 3px; font-size: 8px; color: #94a3b8; }
        .empty-note { border: 1px dashed #cbd5e1; padding: 10px; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header-bar">
        <table>
            <tr>
                <td style="width:56px; text-align:left;">
                    @php $logo = public_path('images/ncmb-logo.svg'); @endphp
                    @if(file_exists($logo))
                        <img src="{{ 'data:image/svg+xml;base64,' . base64_encode(file_get_contents($logo)) }}" class="logo">
                    @endif
                </td>
                <td style="text-align:left;">
                    <div class="agency">NCMB</div>
                    <div class="form-title">Client Satisfaction Measurement (CSM) — Monthly Summary Report</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="meta">
        <b>For the month of:</b> {{ $monthLabel }} &nbsp;|&nbsp; <b>Date generated:</b> {{ now()->format('F j, Y') }} &nbsp;|&nbsp; <b>Scope:</b> All branches
    </div>

    @if(!$hasData)
        <div class="empty-note">
            No survey responses were recorded for {{ $monthLabel }}.
            This report is kept as part of the annual CSM record.
        </div>
        <div class="footer">Generated by the NCMB ICT System &middot; {{ $monthLabel }} &middot; Page 1 of 2</div>
    @else
        <div class="section-title">Monthly Summary</div>
        <table class="rpt-table">
            <tr>
                <th style="width:16%;">Overall Rating</th>
                <th style="width:18%;">Rating Description</th>
                <th style="width:14%;">% Satisfied</th>
                <th style="width:14%;">Responses</th>
                <th style="width:22%;">Completed Requests</th>
                <th>Response Rate</th>
            </tr>
            <tr>
                <td class="avg">{{ $overall !== null ? number_format($overall, 1) . ' / 5' : '&mdash;' }}</td>
                <td>{{ $overall !== null ? $band['label'] : '&mdash;' }}</td>
                <td>{{ $satisfiedPct !== null ? $satisfiedPct . '%' : '&mdash;' }}</td>
                <td>{{ $respondents }}</td>
                <td>{{ $completedCount }}</td>
                <td>{{ $responseRate !== null ? $responseRate . '%' : '&mdash;' }}</td>
            </tr>
        </table>

        <div class="section-title">How Each Question Was Answered</div>
        <table class="rpt-table">
            <tr>
                <th style="width:38%;">Question</th>
                <th>5<span class="sub">Strongly Agree</span></th>
                <th>4<span class="sub">Agree</span></th>
                <th>3<span class="sub">Not sure</span></th>
                <th>2<span class="sub">Disagree</span></th>
                <th>1<span class="sub">Strongly Dis.</span></th>
                <th style="width:9%;">Average</th>
                <th style="width:13%;">Rating</th>
            </tr>
            @foreach($questions as $row)
                <tr>
                    <td class="q">{{ $row['question'] }}</td>
                    @foreach([5,4,3,2,1] as $s)
                        <td>{{ $row['counts'][$s] }}</td>
                    @endforeach
                    <td class="avg">{{ $row['average'] !== null ? number_format($row['average'], 1) : '&mdash;' }}</td>
                    <td>{{ $row['average'] !== null ? $row['band']['label'] : '&mdash;' }}</td>
                </tr>
            @endforeach
            <tr class="total">
                <td class="q">OVERALL SATISFACTION RATING</td>
                <td colspan="5"></td>
                <td class="avg">{{ $overall !== null ? number_format($overall, 1) : '&mdash;' }}</td>
                <td>{{ $overall !== null ? $band['label'] : '&mdash;' }}</td>
            </tr>
        </table>
        <div class="note">
            Scale: 5 = Strongly Agree &middot; 4 = Agree &middot; 3 = Neither Agree nor Disagree &middot; 2 = Disagree &middot; 1 = Strongly Disagree.
            Blank answers (N/A) are not counted.<br>
            Rating: 4.21&ndash;5.00 Very Satisfied &middot; 3.41&ndash;4.20 Satisfied &middot; 2.61&ndash;3.40 Not Sure &middot; 1.81&ndash;2.60 Dissatisfied &middot; 1.00&ndash;1.80 Very Dissatisfied.
        </div>

        <div class="page-break"></div>

        <div class="header-bar">
            <table>
                <tr>
                    <td style="width:56px; text-align:left;">
                        @if(file_exists($logo))
                            <img src="{{ 'data:image/svg+xml;base64,' . base64_encode(file_get_contents($logo)) }}" class="logo">
                        @endif
                    </td>
                    <td style="text-align:left;">
                        <div class="agency">NCMB</div>
                        <div class="form-title">CSM Monthly Summary Report — {{ $monthLabel }} (continued)</div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="section-title">What We Need to Improve</div>
        @if($weakest)
            <div class="sec">
                <p>The clients rated this question the lowest ({{ number_format($weakest['average'], 1) }} — {{ $weakest['band']['label'] }}):</p>
                <p class="q-text">&ldquo;{{ $weakest['question'] }}&rdquo;</p>
                <p>{{ $weakest['disagreeCount'] }} of {{ $respondents }} respondent(s)
                    ({{ $respondents > 0 ? round(($weakest['disagreeCount'] / $respondents) * 100) : 0 }}%)
                    answered Disagree or Strongly Disagree.</p>
                @if($weakest['prevAverage'] !== null)
                    <p>Compared to last month it
                        @if($weakest['average'] < $weakest['prevAverage'])
                            went down ({{ number_format($weakest['prevAverage'], 1) }} &rarr; {{ number_format($weakest['average'], 1) }}).
                        @elseif($weakest['average'] > $weakest['prevAverage'])
                            went up ({{ number_format($weakest['prevAverage'], 1) }} &rarr; {{ number_format($weakest['average'], 1) }}).
                        @else
                            stayed the same ({{ number_format($weakest['average'], 1) }}).
                        @endif
                    </p>
                @else
                    <p>No prior-month sample to compare with yet.</p>
                @endif
                <p>Recommended action: review the process behind this question with the team,
                    then check next month's report to confirm the rating improves.</p>
            </div>
        @endif
        @if($secondWeakest && $weakest && $secondWeakest['column'] !== $weakest['column'] && $secondWeakest['average'] !== null)
            <div class="sec">
                <p>Second-lowest: <span class="q-text">&ldquo;{{ $secondWeakest['question'] }}&rdquo;</span>
                    &mdash; {{ number_format($secondWeakest['average'], 1) }} ({{ $secondWeakest['band']['label'] }}),
                    {{ $secondWeakest['disagreeCount'] }} disagree answer(s).</p>
            </div>
        @endif

        @if($goodNews)
            <div class="section-title">Highest-Rated Questions</div>
            <div class="sec">
                @foreach($goodNews as $row)
                    <p>&bull; &ldquo;{{ $row['question'] }}&rdquo; &mdash; {{ number_format($row['average'], 1) }} ({{ $row['band']['label'] }})</p>
                @endforeach
            </div>
        @endif

        <div class="section-title">Respondent Profile</div>
        <table class="rpt-table">
            <tr>
                <th>Male</th>
                <th>Female</th>
                <th>Not specified</th>
                <th>Total</th>
            </tr>
            <tr>
                @php $others = $respondents - $male - $female; @endphp
                <td>{{ $male }}</td>
                <td>{{ $female }}</td>
                <td>{{ $others > 0 ? $others : 0 }}</td>
                <td>{{ $respondents }}</td>
            </tr>
        </table>

        <div class="footer">Generated by the NCMB ICT System &middot; {{ $monthLabel }} &middot; Page 2 of 2</div>
    @endif

</body>
</html>